### ISSUE TITLE
404 Not Found (Windows 10)

### ISSUE THREAD

**Issue by obfuscatedgenerated** [kawarimidoll/gh-graph#1]
$ gh graph
gh: Not Found (HTTP 404)

**Comment by obfuscatedgenerated** [comment]
I'm assuming this is some issue with the handling of strings, since cURLing the address https://github-contributions-api.deno.dev/obfuscatedgenerated.term manually does work and is not a 404.

**Comment by obfuscatedgenerated** [comment]
Doing some digging I found that the error comes from the line:
USER=$(gh api /user --jq .login)
but running gh api /user --hq .login returns my username as expected. This might just be a compatibility issue with windows.

**Comment by obfuscatedgenerated** [comment]
Reopening to say that replacing
gh api /user --jq .login
for
gh api user --jq .login
works correctly on Windows.

**Comment by obfuscatedgenerated** [comment]
I have opened a PR with the change made. 😄

**Comment by kawarimidoll** [comment]
Thank you for your detailed report and creating PR 🥰
